### ISSUE TITLE
cmake files

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/qtbase-os2#102]
The provided Qt5Gui_*.cmake, Qt5Network_*.cmake, Qt5Sql_*.cmake and Qt5Widgets.cmake contain some errors.

It's a wrong dll name like Qt5Widgets.dll in the Qt5Widgets.cmake case or is points to some .so file like in the other cases.
I suspect a issue in the create_cmake.pref file, where line 148 should contain os2 as well.

**Comment by dmik** [comment]
All works fine now, please test (make needs to be run again).
