### ISSUE TITLE
Decide on O_BINARY for standard I/O streams

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/qtbase-os2#106]
There is some indication that Qt expects standard I/O file streams to be in O_BINARY mode by default while they are in O_TEXT. See https://github.com/bitwiseworks/qtdeclarative-os2/issues/1#issuecomment-530337325 for details.

I need a valid proof of that before I change it.

**Comment by dmik** [comment]
I'm also trying to run the auto-test suite for this part (corelib/io) and getting some minor failures (a 5.13 regression) which need a fix.

**Comment by dmik** [comment]
Tests don't reveal any problem with EOLs so far but I now better understand what's going on in the QML test case. `qmlplugindump` first prepares a QByteArray with all data (and `\n` there as line separators). Then this array is just flushed to `std::cout` if there is no output file (and the test case doesn't provide one so this is what happens there). This makes OS/2 replace `\n` with `\r\n` by default. And this stdout is then read by `QProcess::readAllStandardOutput` which is supposed to convert `\r\n` back to `\n` but apparently it doesn't do that. I need to check why.

**Comment by dmik** [comment]
From what I see, there is nothing wrong actually. `QProcess::readAllStandardOutput` will in fact perform CRLF->LF translation but only if `OpenMode::Text` is given to `QProcess::start` (which makes sense). Once I add `OpenMode::Text` manually to the above test case, all starts working as it should. And there is absolutely no reason to make `Text` a default mode for `QProcess`. It's unknown which kind of data is about to appear on its standard output channels: text or binary.

The mismatch in the test case happens because `qmlplugindump` performs output using the **standard** C++ `cout` channel whose text/binary mode is platform dependent (text on both Windows and OS/2) but input is done using `QProcess` (which as any other `QIODevice` defaults to binary mode). If `qmlplugindump` were using `QFile` to perform output, LF->CRLF translation wouldn't have been done in the first place and all would work w/o adding Text to `QProcess::start`. 

So, all in all, nothing to fix here.

The only thing I wonder is how this test ever succeeds on Windows. But I will leave it for another time. Too much work to check for now.

**Comment by komh** [comment]
I know, on Windows at least MinGW does not output \r\n at all except to a console, but just \n only even if a mode of stdout/stderr is O_TEXT. 

On OS/2, making O_TEXT a default of stdin, and making O_BINARY a default of stdout/stderr if not a console is good strategy.
