### ISSUE TITLE
QEvent::DeferredDelete endlessly wakes up GUI event thread

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/qtbase-os2#121]
While working on https://github.com/bitwiseworks/qtwebengine-chromium-os2/issues/25, I discovered that the presence of `QEvent::DeferredDelete` events in the posted event queue (ones posted by Qt itself to implement `QObject::deleteLater` machinery) prevents the GUI event loop from ever sleeping in `WinGetMsg` while it should not (according to the design).

`QCoreApplicationPrivate::sendPostedEvents` checks if a series of conditions is met before processing DeferredDelete events. And if not, these events are reposted again. Once there is at least one DeferredDelete event int the queue, it will be endlessly reposted (until the event queue returns to an upper level or the app terminates) keeping the posted event queue never empty. This confuses `QEventDispatcherOS2::processEvents` that treats the presence of events there as a signal to not wait for a message but return.

As a result, `QEventDispatcherOS2::processEvents` gets called over and over again in a tight loop creating a 100% CPU load on a single core (25% overall CPU load in case of 4 cores, 50% in case of 2 cores and so on).

**Comment by psmedley** [comment]
I see similar CPU utilisation issues with every qt5 example I've tried so far, from Tellies port of Tetris, to ports of the recoll GUI and gimagereader. I assumed this was a known issue given the beta status of the port.

**Comment by dmik** [comment]
I see. And your assumption is generally right. It's beta indeed. Anyway, I know how to fix it. There is another problem, though: all three of a) docs, b) implementations on different platforms, c) contradict each other. For example,
* Docs say that [`QEventDispatcher::processEvents`](https://doc.qt.io/qt-5/qabstracteventdispatcher.html#processEvents) should return immediately if there are events by the time it is called (after processing all of them). It's not specified which type of events it assumes (system events or those posted with `QCoreApplication::postEvent` or both), but mentioning of "all events" allows to assume that both types of events are processed.
* Exactly the same is assumed by https://github.com/bitwiseworks/qtbase-os2/blob/9180b2a7a57234af52b33d6364743ca856b308b1/tests/auto/corelib/kernel/qeventdispatcher/tst_qeventdispatcher.cpp#L252 which literally expects that posted events are processed by a single `QCoreApplication::processEvents` call (which internally calls `QEventDispatcher::processEvents`).
* However, this code https://github.com/bitwiseworks/qtbase-os2/blob/9180b2a7a57234af52b33d6364743ca856b308b1/src/corelib/kernel/qcoreapplication.cpp#L1722 clearly states that while posted events are indeed processed, the event dispatcher should go to sleep after that. And the code does just what it states. So in theory the `sendPostedEvents` test should never succeed... And it was failing on OS/2 until I fixed it in https://github.com/bitwiseworks/qtbase-os2/commit/2e3988f346288381dbf0114237e261d91086b999 — in full accordance to the docs. And this fix eventually resulted into the problem we are seeing now. This is so confusing.

Anyway, I will fix it so that there is no CPU load and the test is happy too. I just wonder how other platforms survive that.

**Comment by dmik** [comment]
Fix committed, the test build of Qt5Core.dll is here: http://rpm.netlabs.org/test/Qt5Core.7z.

Please test and report if it fixes the issue for you.

**Comment by psmedley** [comment]
Switching out for the new DLL, I get:
qt.qpa.plugin: Could not find the Qt platform plugin "os2" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.


Killed by SIGABRT
pid=0xae8e ppid=0xae89 tid=0x0001 slot=0x0088 pri=0x0200 mc=0x0001 ps=0x0010
U:\DEV\GIMAGEREADER-3.3.1\BUILD\GIMAGEREADER-QT5.EXE
Process dumping was disabled, use DUMPPROC / PROCDUMP to enable it.

**Comment by mediazona-admin** [comment]
Did you drop-in replace it or used BEGINLIBPATH? IIRC it will look for qos2.dll relative to its location. If it’s placed alone, it will not find that one — hence the message you see. Try to replace the RPM dll. Might also not work because default search paths may be different in the RPM build and my local dev build. If it still fails, I will tell you how to fix qt.conf so that it will work.

**Comment by dmik** [comment]
Did you drop-in replace it or used BEGINLIBPATH? It fails because it cannot find qos2.dll and this is looked up in a dir relative to the DLL by default (unless overridden with qt.conf). Please replace the original RPM DLL with it and see if it works. If not, then a change to qt.conf might be needed.

**Comment by psmedley** [comment]
I replaced the rpm dll....

**Comment by dmik** [comment]
Ok, I refreshed my memory. The dev build has all paths hard coded (for a reason), so `qos2.dll` is simply not where it is expected to be on your machine. The only way to use the dev dll in such a case is to overwrite paths with `qt.conf` which you need to put in the app's exe directory (and it's irrelevant where the dev DLL is located, it actually may be under BEGINLIBPATH):
```
[Paths]
Prefix=/@unixroot/usr/lib/qt5
```

**Comment by psmedley** [comment]
Thanks - this fixes the background cpu usage for me.
