### ISSUE TITLE
Implement system clipboard integration

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/qtbase-os2#123]
This is really an important task and should be easy to implement (by copying relevant parts from the Qt 4 port). Virtually any app needs that.

This is surely a must for the Otter browser.

**Comment by josch1710** [comment]
BTW, when I use FeatherPad, I can now copy and paste in both directions.

**Comment by dmik** [comment]
Not sure what you mean by this comment. It works both ways since September 2021 without any extra tools.

**Comment by josch1710** [comment]
Your last comment in this issue was that the clipboard only works in one direction. You closed the issue without further comment, so I assumed you weren't finished ;-)
