### ISSUE TITLE
Fix %{time} in qSetMessagePattern

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/qtbase-os2#6]
Currently, using the `%{time}` placeholder (with any argument) in [`qSetMessagePattern`](http://doc.qt.io/qt-5/qtglobal.html#qSetMessagePattern) is broken. Steps to reproduce:

1. `set QT_MESSAGE_PATTERN=%%{time process}`
2. Issue any `qWarning` from a Qt program.

It was discovered when porting `qmake` (see https://github.com/bitwiseworks/qtbase-os2/issues/1#issuecomment-399454198). Here's the output with `set QT_MESSAGE_PATTERN=[%%{time process}] %%{function}:%%{line}: %%{message}`:

```
[%{time] QFileSystemEngine::fillMetaData:976: Empty filename passed to function
```

I.e. `%{time` is printed instead the requested time value. Note that the other placeholders (`%{function}` etc) are handled well.

**Comment by SilvanScherrer** [comment]
I had a quick look at the source https://github.com/bitwiseworks/qtbase-os2/blob/master/src/corelib/global/qlogging.cpp and %{time is only working when not in the bootstrap phase.

**Comment by dmik** [comment]
You are right. With the full-featured QtCore DLL this test app:
``` c++
#include <QCoreApplication>
#include <QDebug>

int main (int argc, char ** argv)
{
  qSetMessagePattern ("[%{time process}] %{function}:%{line}: %{message}");

  qDebug () << "Hello";

  return 0;
}
```
works well. I get this on output:
```
[     0.027] main:8: Hello
```

BTW I built this test using the following .pro:
``` qmake
TEMPLATE = app

CONFIG += console
QT = core

SOURCES += main.cpp
```
Which means that the general qmake infrastructure works too.

Closing this as "not a bug".
