### ISSUE TITLE
Build platform plugins

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/qtbase-os2#77]
These are located in `src/plugins/platforms`.

See https://github.com/bitwiseworks/qtbase-os2/issues/75#issuecomment-480004813 for more info.

**Comment by dmik** [comment]
With the above commit, universal crorss-platform plugins build. Now comes the hard part: creating an OS/2-specific plugin that will provide integration with the Presentation Manager (that used to be scattered among separate GUI and Widget classes in Qt 4).

**Comment by dmik** [comment]
With the above commit, all builds and we get a nice platform plugin named `qos2.dll`. It's still a skeleton marking the minimal interface that needs to be implemented (which will be next steps).

**Comment by dmik** [comment]
JFYI, I'm planning to put the Dive support into the OS/2 platform plugin right from the beginning and here is the relative Qt 4 ticket that contains a lot of useful information: http://trac.netlabs.org/qt4/ticket/101 — the main class doing Dive it in Qt 4 is `QPMDiveWindowSurface`. When DIVE is not available, it falls back to the old method using `GpiDrawBits` (this is implemented within `QRasterWindowSurface` in Qt 4).

Frankly, I would like to avoid doing a `GpiDrawBits` fallback at all in Qt 5 assuming that DIVE is already present on our target eCS and ArcaOS systems. However, the question is Panorama as it used to be a problem back then (9 years ago!) so that I had to disable DIVE on Panorama by default. I need to recheck it on my ArcaOS install to see how it goes now.

**Comment by dmik** [comment]
Hmm, I did a quick check and, unfortunately, Panorama under ArcaOS 3.x is as bad as it was 9 years ago. None of DIVE modes are usable here. This makes me invert my logic: I will **not** spend time on DIVE now at all as virtally all ArcaOS installs use the Panorama video driver. I will go the `GpiDrawBits` way only.

**Comment by guzzi-g5** [comment]
There are still plans to add new chipsets to SNAP.

**Comment by dmik** [comment]
With the above commit, both Qt GUI example applications (rasterwindow and analogclock) work fine meaning that the window painting part is basically done. There is, however, one strange effect noticed by Lars Erdmann, I will create a new ticket for it.

Remaining parts are keyboard and mouse input as well as syncing window property changes between PM and Qt. Will create separate tickets for that too.

**Comment by dmik** [comment]
It's actually enough for this ticket as the platform plugin for OS/2 now builds and provides basic functionality. Further work will be done in separate tickets (see above).
