### ISSUE TITLE
Use PM fonts and colors

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/qtbase-os2#85]
We should use system-specified window fonts and colors for the default Qt theme as we used to do this for Qt 4.

**Comment by dmik** [comment]
Fonts and colors done. Looks much better now, compare the screen shots.

The only problem so far is that embedded bitmaps for selected sizes of the `Workplace Sans` font are not enabled now (so that the menu font looks a bit blurred). In Qt4 we didn't use fontconfig and enabled embedded bitnamps manually for all fonts when creating freetype instances. But now fontconfig is involved and it somehow doesn't want to get it enabled. Needs some debugging. 

![01-win](https://user-images.githubusercontent.com/900726/58506360-d0860680-8197-11e9-8792-1170b09363db.png)

![hwnd_80000307_0](https://user-images.githubusercontent.com/900726/58506377-da0f6e80-8197-11e9-88ff-8fb91cc63103.png)

**Comment by dmik** [comment]
I've fixed the embedded bitmap issue in the commit above. For some reason this code was simply dropped from Qt 5 (while even the respective variable was left untouched!). Really strange and makes no sense.

Anyway, now this looks as it should:

![hwnd_80000172_0](https://user-images.githubusercontent.com/900726/58652503-677bcb80-831c-11e9-97f0-b41e5381e67f.png)

Note though that, given that we use our nice fontconfig port in Qt 5 to unify font handling across various ports, a slight modification to the `WarpSans` substitution setting is needed that will enable
proper hinting to make bitmaps from `Workplace Sans` look exactly like `WarpSans`. (In Qt 4 we only used FreeType and had hinting always set to full). Here's the respetive fontconfig commit: https://github.com/bitwiseworks/fontconfig-os2/commit/9615bed8a378aca47ed67ef13ce9edcf8d28d363.

Please wait for a new fontconfig RPM to be released or replace `%UNIXROOT%\etc\fonts\30-warpsans.conf` with a new file with the following contents if you want the fix now:
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <!--
    WarpSans is the standard OS/2 bitmap font used as the main UI font in
    recent OS/2 versions but this format is not supported by FreeType.
    There is a TTF replacement for it created by Alex Taylor called
    Workplace Sans (with hinting and nice bitmaps for certain sizes).
  -->
  <alias binding="same">
    <family>WarpSans</family>
    <accept><family>Workplace Sans</family></accept>
    <default><family>Helvetica</family></default>
  </alias>
  <match target="font">
    <test qual="any" name="family">
      <string>Workplace Sans</string>
    </test>
    <!--
      Workplace Sans provides nice embedded bitmaps for small glyph sizes
      to mimic WarpSans appearance 1 to 1. Make sure they are enabled.
      Note that hinting is also a must to keep appearance identical.
    -->
    <edit name="embeddedbitmap" mode="assign">
      <bool>true</bool>
    </edit>
    <edit name="hintstyle" mode="assign">
      <const>hintnone</const>
    </edit>
  </match>
</fontconfig>
```
Here is how it looks without and with the above fix (note that letters hit each other on the left screenshot):

![Снимок экрана 2019-05-30 в 21 06 57](https://user-images.githubusercontent.com/900726/58653721-fab60080-831e-11e9-886a-11256273a5e6.png)

All in all, now Qt 5 apps look pretty much the same as native PM apps in terms of fonts and colors. I guess that's more than enough for this task. Closing it.

**Comment by dryeo** [comment]
I copied and pasted the above into my fonts.conf, a minute later SeaMonkey and Thunderbird both crashed, OOM (INT 3). After rebooting neither would start with the same trp. Reverting fonts.conf allowed both to run.
Tried to look at your commits, both gave a 404 error and looking at the bitwise page, I didn't see any fontconfig repository. Did you accidentally make it private?

**Comment by dmik** [comment]
Here Firefox and all others works well with this change. Which version of fontconfig are you using? There was a merge conflict in 2.13.1-1 which made it crash. Fixed in 2.13.1-2.

**Comment by dryeo** [comment]
I'm still using 2.12.4-1. I'll try updating and updating fonts.conf It's 
also possible that copy and pasting had an error which was why I was 
hoping to see the actual patch.

**Comment by dryeo** [comment]
OK, after updating fontconfig and freetype, things seem stable with the updated warpsans-conf.
