### ISSUE TITLE
Long dll names...

### ISSUE THREAD

**Issue by TeLLie** [bitwiseworks/qtbase-os2#92]
Hello,
When i try to build the latest source i notice there are still + 8 digits dll names.

F:\qt5-dev\config.tests\reduce_exports\reduce_exports.dll
F:\qt5-dev\plugins\bearer\qgenericbearer.dll
F:\qt5-dev\plugins\generic\qtuiotouchplugin.dll
F:\qt5-dev\plugins\platforminputcontexts\ibusplatforminputcontextplugin.dll
F:\qt5-dev\plugins\platforms\qoffscreen.dll

**Comment by TeLLie** [comment]
After building Qt5 completed, i found one more:
config.tests\reduce_exports\reduce_exports.dll

**Comment by dmik** [comment]
All done, there was even some more.
